
"use client";

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Users, FileUp, UserPlus, Edit, Trash2, AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { useForm, SubmitHandler } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { useToast } from '@/hooks/use-toast';
import type { UserProfile } from '@/types';
import { Switch } from '@/components/ui/switch';
import { auth, db } from '@/lib/firebase';
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { collection, addDoc, getDocs, doc, setDoc, updateDoc, deleteDoc, query, where, Timestamp } from 'firebase/firestore';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

const adminSchema = z.object({
  // uid will be generated by Firebase Auth, not part of form schema for add
  id: z.string().min(1, "ID Aplikasi Admin tidak boleh kosong (cth: ADMIN00X)").optional(), // App-specific ID
  fullName: z.string().min(3, "Nama lengkap minimal 3 karakter"),
  email: z.string().email("Format email tidak valid"),
  passwordValue: z.string().min(6, "Password minimal 6 karakter").optional().or(z.literal('')),
});

// For edit, password is not directly changed here.
const editAdminSchema = adminSchema.omit({ passwordValue: true });

type AdminFormData = z.infer<typeof adminSchema>;
type EditAdminFormData = z.infer<typeof editAdminSchema>;


export default function ManageAdminsPage() {
  const { toast } = useToast();
  const [admins, setAdmins] = useState<UserProfile[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isAddAdminDialogOpen, setIsAddAdminDialogOpen] = useState(false);
  const [isEditAdminDialogOpen, setIsEditAdminDialogOpen] = useState(false);
  const [currentEditingAdmin, setCurrentEditingAdmin] = useState<UserProfile | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [firebaseError, setFirebaseError] = useState<string | null>(null);

  const { register, handleSubmit, reset, formState: { errors }, setValue } = useForm<AdminFormData>({
    resolver: zodResolver(adminSchema),
  });

  const { register: registerEdit, handleSubmit: handleSubmitEdit, reset: resetEdit, formState: { errors: errorsEdit }, setValue: setValueEdit } = useForm<EditAdminFormData>({
    resolver: zodResolver(editAdminSchema),
  });

  const fetchAdmins = async () => {
    setIsLoading(true);
    setFirebaseError(null);
    try {
      const q = query(collection(db, "users"), where("role", "==", "Admin"));
      const querySnapshot = await getDocs(q);
      const adminList: UserProfile[] = [];
      querySnapshot.forEach((doc) => {
        // doc.id is the Firebase Auth UID
        adminList.push({ uid: doc.id, ...doc.data() } as UserProfile);
      });
      setAdmins(adminList);
    } catch (error: any) {
      console.error("Error fetching admins: ", error);
      setFirebaseError("Gagal memuat data Admin. Periksa koneksi atau coba lagi nanti.");
      toast({ title: "Error Memuat Data", description: error.message, variant: "destructive" });
    }
    setIsLoading(false);
  };

  useEffect(() => {
    fetchAdmins();
  }, []);

  const handleAddAdmin: SubmitHandler<AdminFormData> = async (data) => {
    if (!data.passwordValue) {
      toast({ title: "Password Dibutuhkan", description: "Password awal wajib diisi untuk admin baru.", variant: "destructive" });
      return;
    }

    // Check if app-specific ID already exists
    if (data.id && admins.some(admin => admin.id === data.id)) {
      toast({ title: "Gagal Menambahkan", description: `ID Aplikasi Admin ${data.id} sudah ada.`, variant: "destructive"});
      return;
    }
     // Check if email already exists in Firebase Auth (more robust check than just local state)
    const existingEmailUser = admins.find(admin => admin.email === data.email);
    if (existingEmailUser) {
        toast({ title: "Gagal Menambahkan", description: `Email ${data.email} sudah terdaftar.`, variant: "destructive"});
        return;
    }


    try {
      // 1. Create user in Firebase Authentication
      const userCredential = await createUserWithEmailAndPassword(auth, data.email, data.passwordValue);
      const firebaseUser = userCredential.user;

      if (firebaseUser) {
        // 2. Create user profile in Firestore
        const appAdminId = data.id && data.id.trim() !== '' ? data.id : `ADMIN${String(Date.now()).slice(-6)}`;
        const newAdminProfile: Omit<UserProfile, 'uid'> = {
          id: appAdminId, // App-specific ID
          fullName: data.fullName,
          email: data.email,
          role: 'Admin',
          status: 'Aktif',
          joinDate: Timestamp.now().toDate().toISOString(), // Or a form field
          // No passwordValue is stored in Firestore
        };

        // Use Firebase Auth UID as document ID in Firestore
        await setDoc(doc(db, "users", firebaseUser.uid), newAdminProfile);

        toast({ title: "Admin Ditambahkan", description: `Admin ${data.fullName} (Email: ${data.email}) berhasil ditambahkan.` });
        fetchAdmins(); // Refresh list
        reset({ id: '', fullName: '', email: '', passwordValue: '' });
        setIsAddAdminDialogOpen(false);
      }
    } catch (error: any) {
      console.error("Error adding admin: ", error);
      let errorMessage = "Gagal menambahkan admin.";
      if (error.code === 'auth/email-already-in-use') {
        errorMessage = "Email ini sudah terdaftar. Gunakan email lain.";
      } else if (error.code === 'auth/weak-password') {
        errorMessage = "Password terlalu lemah. Gunakan minimal 6 karakter.";
      }
      toast({ title: "Error", description: errorMessage, variant: "destructive" });
    }
  };

  const handleOpenEditDialog = (admin: UserProfile) => {
    setCurrentEditingAdmin(admin);
    setValueEdit('id', admin.id); // app-specific ID
    setValueEdit('fullName', admin.fullName);
    setValueEdit('email', admin.email || '');
    // Password is not edited here
    setIsEditAdminDialogOpen(true);
  };

  const handleEditAdmin: SubmitHandler<EditAdminFormData> = async (data) => {
    if (!currentEditingAdmin || !currentEditingAdmin.uid) return;

    // Check if new app-specific ID conflicts (if it's being changed and editable)
    if (data.id && data.id !== currentEditingAdmin.id && admins.some(admin => admin.id === data.id && admin.uid !== currentEditingAdmin.uid)) {
      toast({ title: "Gagal Memperbarui", description: `ID Aplikasi Admin ${data.id} sudah digunakan oleh admin lain.`, variant: "destructive"});
      return;
    }
    // Check if new email conflicts with other users (excluding the current user)
    if (data.email && data.email !== currentEditingAdmin.email && admins.some(admin => admin.email === data.email && admin.uid !== currentEditingAdmin.uid)) {
        toast({ title: "Gagal Memperbarui", description: `Email ${data.email} sudah digunakan oleh admin lain.`, variant: "destructive"});
        return;
    }


    try {
      const adminDocRef = doc(db, "users", currentEditingAdmin.uid);
      const updatedData: Partial<UserProfile> = {
        fullName: data.fullName,
        email: data.email,
        // id: data.id, // Only update if app-specific ID is editable
      };
      // Note: Changing email in Firestore should ideally be synced with Firebase Auth email change (updateEmail)
      // which requires re-authentication. For simplicity, we're only updating Firestore here.
      // A more robust solution might involve a Firebase Function or a clearer UX that email changes require verification.

      await updateDoc(adminDocRef, updatedData);
      toast({ title: "Admin Diperbarui", description: `Data Admin ${data.fullName} berhasil diperbarui.` });
      fetchAdmins(); // Refresh list
      resetEdit({ id: '', fullName: '', email: '' });
      setIsEditAdminDialogOpen(false);
      setCurrentEditingAdmin(null);
    } catch (error: any) {
      console.error("Error updating admin: ", error);
      toast({ title: "Error", description: `Gagal memperbarui admin: ${error.message}`, variant: "destructive" });
    }
  };
  
  const handleDeleteAdmin = async (adminToDelete: UserProfile) => {
    if (!adminToDelete.uid) {
        toast({ title: "Error", description: "UID Admin tidak ditemukan.", variant: "destructive" });
        return;
    }
    // Simple confirmation, ideally use a more robust confirmation dialog
    if (!window.confirm(`Apakah Anda yakin ingin menghapus Admin ${adminToDelete.fullName}? Tindakan ini tidak dapat diurungkan.`)) {
        return;
    }

    try {
        // Delete Firestore document
        await deleteDoc(doc(db, "users", adminToDelete.uid));
        
        // IMPORTANT: Deleting the Firebase Auth user is a separate, more complex operation.
        // It typically requires Admin SDK privileges (server-side function) to delete another user.
        // For now, we are only deleting the Firestore profile.
        // This means the Auth user will still exist and can log in, but won't have a profile/role in the app.
        toast({ title: "Admin Dihapus (Profil)", description: `Profil Admin ${adminToDelete.fullName} telah dihapus dari Firestore.` });
        fetchAdmins(); // Refresh list
    } catch (error: any) {
        console.error("Error deleting admin profile: ", error);
        toast({ title: "Error Menghapus Profil", description: `Gagal menghapus profil admin: ${error.message}`, variant: "destructive" });
    }
};


  const handleImportAdmins = () => {
    toast({ title: "Fitur Dalam Pengembangan", description: "Impor Admin dari Excel belum diimplementasikan." });
  };

  const handleStatusChange = async (adminToUpdate: UserProfile, newStatusActive: boolean) => {
    if (!adminToUpdate.uid) {
      toast({ title: "Error", description: "UID Admin tidak ditemukan.", variant: "destructive" });
      return;
    }
    const newStatus = newStatusActive ? 'Aktif' : 'Nonaktif';
    try {
      const adminDocRef = doc(db, "users", adminToUpdate.uid);
      await updateDoc(adminDocRef, { status: newStatus });
      toast({
        title: "Status Admin Diperbarui",
        description: `Status admin ${adminToUpdate.fullName} telah diubah menjadi ${newStatus}.`,
      });
      fetchAdmins(); // Refresh list
      // Note: Disabling/Enabling user in Firebase Auth is a separate operation (user.disabled property via Admin SDK)
    } catch (error: any) {
      console.error("Error updating admin status: ", error);
      toast({ title: "Error", description: `Gagal memperbarui status admin: ${error.message}`, variant: "destructive" });
    }
  };

  const filteredAdmins = admins.filter(admin =>
    admin.fullName.toLowerCase().includes(searchTerm.toLowerCase()) ||
    admin.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (admin.email && admin.email.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader className="flex flex-col sm:flex-row justify-between items-start sm:items-center">
          <div>
            <CardTitle className="flex items-center text-2xl text-primary">
              <Users className="mr-3 h-7 w-7" />
              Manajemen Akun Admin
            </CardTitle>
            <CardDescription>
              Kelola akun pengguna dengan peran Admin. Data disimpan di Firestore.
            </CardDescription>
          </div>
          <Dialog open={isAddAdminDialogOpen} onOpenChange={setIsAddAdminDialogOpen}>
            <DialogTrigger asChild>
              <Button className="mt-2 sm:mt-0 w-full sm:w-auto" onClick={() => reset({ id: '', fullName: '', email: '', passwordValue: '' })}>
                <UserPlus className="mr-2 h-4 w-4" /> Tambah Admin Baru
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[425px]">
              <DialogHeader>
                <DialogTitle>Tambah Admin Baru</DialogTitle>
                <DialogDescription>Isi detail untuk Admin baru. Akun akan dibuat di Firebase.</DialogDescription>
              </DialogHeader>
              <form onSubmit={handleSubmit(handleAddAdmin)} className="space-y-4 py-4">
                <div>
                  <Label htmlFor="addAdminAppId">ID Aplikasi Admin (Opsional)</Label>
                  <Input id="addAdminAppId" {...register("id")} placeholder="Otomatis jika kosong (cth: ADMINXXXXX)" />
                  {errors.id && <p className="text-destructive text-sm mt-1">{errors.id.message}</p>}
                </div>
                <div>
                  <Label htmlFor="addAdminFullName">Nama Lengkap <span className="text-destructive">*</span></Label>
                  <Input id="addAdminFullName" {...register("fullName")} />
                  {errors.fullName && <p className="text-destructive text-sm mt-1">{errors.fullName.message}</p>}
                </div>
                <div>
                  <Label htmlFor="addAdminEmail">Email (untuk Login) <span className="text-destructive">*</span></Label>
                  <Input id="addAdminEmail" type="email" {...register("email")} />
                  {errors.email && <p className="text-destructive text-sm mt-1">{errors.email.message}</p>}
                </div>
                <div>
                  <Label htmlFor="addAdminPassword">Password Awal <span className="text-destructive">*</span></Label>
                  <Input id="addAdminPassword" type="password" {...register("passwordValue")} />
                  {errors.passwordValue && errors.passwordValue.message !== '' && <p className="text-destructive text-sm mt-1">{errors.passwordValue.message}</p>}
                </div>
                <DialogFooter>
                  <Button type="button" variant="outline" onClick={() => { reset(); setIsAddAdminDialogOpen(false); }}>Batal</Button>
                  <Button type="submit">Simpan Admin</Button>
                </DialogFooter>
              </form>
            </DialogContent>
          </Dialog>
        </CardHeader>
        <CardContent>
          {firebaseError && (
            <Alert variant="destructive" className="mb-4">
              <AlertCircle className="h-4 w-4" />
              <AlertTitle>Error Terjadi</AlertTitle>
              <AlertDescription>{firebaseError}</AlertDescription>
            </Alert>
          )}
          <div className="mb-4">
            <Input
              placeholder="Cari Admin (ID Aplikasi, Nama, Email)..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="max-w-sm"
            />
          </div>
          {isLoading ? (
            <p>Memuat data admin...</p>
          ) : (
            <>
            <Card className="border shadow-sm">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>ID Aplikasi</TableHead>
                    <TableHead>Nama Lengkap</TableHead>
                    <TableHead>Email</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="text-center">Aksi</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredAdmins.length > 0 ? filteredAdmins.map((admin) => (
                    <TableRow key={admin.uid}>
                      <TableCell className="font-medium">{admin.id}</TableCell>
                      <TableCell>{admin.fullName}</TableCell>
                      <TableCell>{admin.email}</TableCell>
                      <TableCell>
                        <Switch
                          checked={admin.status === 'Aktif'}
                          onCheckedChange={(newStatus) => handleStatusChange(admin, newStatus)}
                          aria-label={`Status admin ${admin.fullName}`}
                        />
                        <span className={`ml-2 text-xs ${admin.status === 'Aktif' ? 'text-green-600' : 'text-red-600'}`}>
                          {admin.status}
                        </span>
                      </TableCell>
                      <TableCell className="text-center space-x-1">
                        <Button variant="outline" size="icon" className="h-8 w-8" onClick={() => handleOpenEditDialog(admin)}><Edit size={16}/></Button>
                        <Button variant="destructive" size="icon" className="h-8 w-8" onClick={() => handleDeleteAdmin(admin)}><Trash2 size={16}/></Button>
                      </TableCell>
                    </TableRow>
                  )) : (
                    <TableRow>
                      <TableCell colSpan={5} className="text-center text-muted-foreground">Tidak ada data Admin yang cocok dengan pencarian.</TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            </Card>
            <p className="text-xs text-muted-foreground text-center mt-4">
              Menampilkan {filteredAdmins.length} dari {admins.length} Admin.
            </p>
            </>
          )}
        </CardContent>
      </Card>
      
      <Dialog open={isEditAdminDialogOpen} onOpenChange={(open) => {
          if (!open) setCurrentEditingAdmin(null);
          setIsEditAdminDialogOpen(open);
      }}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Edit Admin: {currentEditingAdmin?.fullName}</DialogTitle>
            <DialogDescription>Perbarui detail Admin. ID Aplikasi dan Email dapat diubah. Perubahan email di sini hanya di profil Firestore, tidak mengubah email login Firebase Auth.</DialogDescription>
          </DialogHeader>
          <form onSubmit={handleSubmitEdit(handleEditAdmin)} className="space-y-4 py-4">
            <div>
              <Label htmlFor="editAdminAppId">ID Aplikasi Admin</Label>
              <Input id="editAdminAppId" {...registerEdit("id")} />
              {/* ID Aplikasi bisa diedit atau tidak, tergantung kebijakan. Jika unik, perlu validasi. */}
              {errorsEdit.id && <p className="text-destructive text-sm mt-1">{errorsEdit.id.message}</p>}
            </div>
            <div>
              <Label htmlFor="editAdminFullName">Nama Lengkap <span className="text-destructive">*</span></Label>
              <Input id="editAdminFullName" {...registerEdit("fullName")} />
              {errorsEdit.fullName && <p className="text-destructive text-sm mt-1">{errorsEdit.fullName.message}</p>}
            </div>
            <div>
              <Label htmlFor="editAdminEmail">Email <span className="text-destructive">*</span></Label>
              <Input id="editAdminEmail" type="email" {...registerEdit("email")} />
              {errorsEdit.email && <p className="text-destructive text-sm mt-1">{errorsEdit.email.message}</p>}
               <p className="text-xs text-muted-foreground mt-1">Mengubah email di sini tidak mengubah email login Firebase Auth.</p>
            </div>
            {/* Password tidak diubah di form edit ini */}
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => { resetEdit(); setIsEditAdminDialogOpen(false); setCurrentEditingAdmin(null); }}>Batal</Button>
              <Button type="submit">Simpan Perubahan</Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center text-xl">
            <FileUp className="mr-2 h-5 w-5 text-primary" />
            Impor Admin dari Excel
          </CardTitle>
          <CardDescription>
            Tambahkan beberapa akun admin sekaligus menggunakan file Excel.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <Label htmlFor="excel-file-admin">Pilih File Excel (.xlsx)</Label>
            <Input id="excel-file-admin" type="file" accept=".xlsx, .xls" className="mt-1" />
          </div>
          <p className="text-xs text-muted-foreground">
            Format kolom yang diharapkan: ID Aplikasi Admin (opsional), Nama Lengkap, Email (untuk login), Password Awal.
          </p>
          <Button onClick={handleImportAdmins} className="w-full sm:w-auto">
            <FileUp className="mr-2 h-4 w-4" /> Impor Data Admin
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}

    